#
# @(#)Makefile	1.4 04/08/19
#
# Project Name Project
#
# Author:  Govind Thirumalai
#
#



include $(JAVA_DEV_ROOT)/makefiles/Makefile.include
PACKAGE = app.menu

SOURCE  = \
	MenuException.java \
	Menu.java \
	MenuTag.java \
	SimpleMenu.java \
	CompositeMenu.java \
	XMLMenuTag.java \
	JDBCMenuTag.java \
	MenuBuilder.java \
	XMLMenuBuilder.java \
	JDBCMenuBuilder.java \
	AppMenuBuilder.java \
	AppMenuTag.java \
	

RMI_SOURCE =

MAIN =

include $(JAVA_DEV_ROOT)/makefiles/Makefile.rules
