#
# @(#)Makefile	1.4 04/08/19
#
# Project Name Project
#
# Author: Govind Thirumalai 
#
#



include $(JAVA_DEV_ROOT)/makefiles/Makefile.include
PACKAGE = app.appdb

SOURCE  = \
	  PersistentUsers.java \
	PersistentParticipantEvent.java \
	PersistentRegistrantEvent.java \
	PersistentAgeCategory.java \
	PersistentBeneficiary.java \
	PersistentBloodGroup.java \
	PersistentEventType.java \
	PersistentGender.java \
	PersistentMedal.java \
	PersistentParticipant.java \
	PersistentPaymentStatus.java \
	PersistentPaymentType.java \
	PersistentRegistrant.java \
	PersistentRegistrantPayment.java \
	PersistentRegistrationClass.java \
	PersistentRegistrationSource.java \
	PersistentRegistrationType.java \
	PersistentResult.java \
	PersistentTShirtSize.java \
	PersistentEvent.java \
	  PersistentRole.java \
	  PersistentMenu.java \
	  PersistentAcl.java \

RMI_SOURCE =

MAIN =

include $(JAVA_DEV_ROOT)/makefiles/Makefile.rules
