#
# @(#)Makefile	1.4 04/08/19
#
# Project Name Project
#
# Author: Govind Thirumalai 
#
#



include $(JAVA_DEV_ROOT)/makefiles/Makefile.include
PACKAGE = app.appdb

SOURCE  = \
	  PersistentUsers.java \
	  PersistentRole.java \
	  PersistentMenu.java \
	  PersistentAcl.java \

RMI_SOURCE =

MAIN =

include $(JAVA_DEV_ROOT)/makefiles/Makefile.rules
