#
# @(#)Makefile	1.4 04/08/19
#
# Project Name Project
#
# Author: Govind Thirumalai
#
#



include $(JAVA_DEV_ROOT)/makefiles/Makefile.include
PACKAGE = app.busobj

SOURCE  = \
	UsersObject.java \
	ParticipantEventObject.java \
	RegistrantEventObject.java \
	AgeCategoryObject.java \
	BeneficiaryObject.java \
	BloodGroupObject.java \
	EventTypeObject.java \
	GenderObject.java \
	MedalObject.java \
	ParticipantObject.java \
	PaymentStatusObject.java \
	PaymentTypeObject.java \
	RegistrantObject.java \
	RegistrantPaymentObject.java \
	RegistrationClassObject.java \
	RegistrationSourceObject.java \
	RegistrationTypeObject.java \
	ResultObject.java \
	TShirtSizeObject.java \
	EventObject.java \
	RoleObject.java \
	MenuObject.java \
	AclObject.java \
	
RMI_SOURCE =

MAIN =

include $(JAVA_DEV_ROOT)/makefiles/Makefile.rules
