#
# @(#)Makefile	1.14 04/08/24
#
# Project Name Project
#
# Author: Govind Thirumalai
#
#


include $(JAVA_DEV_ROOT)/makefiles/Makefile.include

# This is relative to public_html dir.
JSP = 

JSP_SOURCE  = \
	Error.jsp \
	InvalidatePage.jsp \
	validation.js \
	common_utils.js \
	Navigation.jsp \
	Header.jsp \
	LeaderBoard.jsp \
	LeftWideSkyScraper.jsp \
	RightWideSkyScraper.jsp \
	Footer.jsp \
	Login.jsp \
	Registration.jsp \
	ResetPassword.jsp \
	Logout.jsp \
	Notes.jsp \
	main.css \
	default.css \
	default.ultimate.css \
	dropdown.css \
	helper.css \
	ManageUsers.jsp \
	ManageMenu.jsp \
	ManageAcl.jsp \
	ManageRole.jsp \

RMI_SOURCE =

MAIN =

include $(JAVA_DEV_ROOT)/makefiles/Makefile.rules
