#
# @(#)Makefile	1.3 04/03/02
#
# Project Name Project
#
# Author: Govind Thirumalai
#
#


#

include $(JAVA_DEV_ROOT)/makefiles/Makefile.include
PACKAGE = core.ConnectionPool

SOURCE  = \
	ConnectionPool.java \
	LogWriter.java

RMI_SOURCE =

MAIN =

include $(JAVA_DEV_ROOT)/makefiles/Makefile.rules
