#
# @(#)Makefile	1.4 04/08/19
#
# Project Name Project
#
# Author: Govind Thirumalai
#
#


include $(JAVA_DEV_ROOT)/makefiles/Makefile.include
PACKAGE = app.businterface

SOURCE  = \
	UsersInterface.java \
	RoleInterface.java \
	MenuInterface.java \
	AclInterface.java \
	SpreadSheetInterface.java \

RMI_SOURCE =

MAIN =

include $(JAVA_DEV_ROOT)/makefiles/Makefile.rules
