#
# @(#)Makefile	1.3 04/03/02
#
# Project Name Project
#
# Author: Govind Thirumalai 
#
#

include $(JAVA_DEV_ROOT)/makefiles/Makefile.include
PACKAGE = core.ui

SOURCE  = \
	AnchorElement.java \
	BlinkElement.java \
	BoldElement.java \
	BreakElement.java \
	CaptionElement.java \
	CenteredElement.java \
	HTMLElement.java \
	HTMLElementObject.java \
	HeadingElement.java \
	HorizontalRuleElement.java \
	ImageElement.java \
	InputElement.java \
	ItalicElement.java \
	ParagraphElement.java \
	SelectElement.java \
	StringElement.java \
	TableDataElement.java \
	TableElement.java \
	TableHeadingElement.java \
	TableRowElement.java \
	TextareaElement.java \
	UnderlineElement.java \
	UnorderedListElement.java \
	DivElement.java \

RMI_SOURCE =

MAIN =

include $(JAVA_DEV_ROOT)/makefiles/Makefile.rules
