#
# @(#)Makefile	1.4 04/08/19
#
# Project Name Project
#
# Author: Govind Thirumalai
#
#



include $(JAVA_DEV_ROOT)/makefiles/Makefile.include
PACKAGE = app.appui

SOURCE  = \
	AppUtilBean.java \
	LoginBean.java \
	NotesBean.java \
	UsersBean.java \
	ParticipantEventBean.java \
	RegistrantEventBean.java \
	AgeCategoryBean.java \
	BeneficiaryBean.java \
	BloodGroupBean.java \
	EventBean.java \
	EventTypeBean.java \
	GenderBean.java \
	MedalBean.java \
	ParticipantBean.java \
	PaymentStatusBean.java \
	PaymentTypeBean.java \
	RegistrantBean.java \
	RegistrantPaymentBean.java \
	RegistrationClassBean.java \
	RegistrationSourceBean.java \
	RegistrationTypeBean.java \
	ResultBean.java \
	TShirtSizeBean.java \
	RegistrationBean.java \
	ResetPasswordBean.java \
	RoleBean.java \
	MenuBean.java \
	AclBean.java \

RMI_SOURCE =

MAIN =

include $(JAVA_DEV_ROOT)/makefiles/Makefile.rules
