#
# @(#)Makefile	1.4 04/08/19
#
# Project Name Project
#
# Author: Govind Thirumalai
#
#



include $(JAVA_DEV_ROOT)/makefiles/Makefile.include
PACKAGE = app.appui

SOURCE  = \
	AppUtilBean.java \
	LoginBean.java \
	NotesBean.java \
	UsersBean.java \
	RegistrationBean.java \
	ResetPasswordBean.java \
	RoleBean.java \
	MenuBean.java \
	AclBean.java \

RMI_SOURCE =

MAIN =

include $(JAVA_DEV_ROOT)/makefiles/Makefile.rules
