#
# @(#)Makefile	1.7 04/03/02
#
# Project Name Project
#
# Author: Govind Thirumalai 
#
#



include $(JAVA_DEV_ROOT)/makefiles/Makefile.include
PACKAGE = core.appdb

SOURCE  = \
	PersistentId.java  \

RMI_SOURCE =

MAIN =


include $(JAVA_DEV_ROOT)/makefiles/Makefile.rules
