#
# @(#)Makefile	1.5 04/08/19
#
# Project Name Project
#
# Author: Govind Thirumalai 
#
#
#


include $(JAVA_DEV_ROOT)/makefiles/Makefile.include
PACKAGE = app.busimpl

SOURCE  = \
	UsersImpl.java \
	RoleImpl.java \
	MenuImpl.java \
	AclImpl.java \


RMI_SOURCE =

MAIN =

include $(JAVA_DEV_ROOT)/makefiles/Makefile.rules
