#***************************************************************************
#
#  Project Name Project - Common Rules Makefile
#  Author : Govind Thirumalai 
#
#***************************************************************************

#***************************************************************************
#
#  Section 3. Rules and dependencies.
#
#  This section defines the exact rules for creating a target file from
#  a (set of) source file(s). The rules can be quite complex and the
#  makefile syntax is not extreamly readable. A quick crash course:
#
#  target : depends
#    rule
#
#  target  - the parameter given to make: What to build
#  depends - file or other targets target depends on
#  rule    - how to create target
#  $(VAR)  - environment variable or variable defined above
#  $@      - Current target
#  $*      - Current target without extension
#  $<      - Current dependency
#
#***************************************************************************

PACKAGE_LOC     = $(subst .,/,$(PACKAGE))
PACKAGE_DIR     = $(DESTINATION)/$(PACKAGE_LOC)
JAVA_FILES      = $(filter  %.java,$(SOURCE))
NONJAVA_FILES   = $(patsubst %.java,,$(SOURCE))
CLASS_FILES     = $(JAVA_FILES:%.java=$(PACKAGE_DIR)/%.class)
OTHER_FILES     = $(NONJAVA_FILES:%=$(PACKAGE_DIR)/%)
JNI_CLASS_FILES = $(JNI_SOURCE:%.java=$(PACKAGE_DIR)/%.class)
JNI_HEADERS     = $(JNI_SOURCE:%.java=%.h)
RMI_CLASS_FILES = $(RMI_SOURCE:%.java=$(PACKAGE_DIR)/%.class)
RMI_STUB_FILES  = $(RMI_SOURCE:%.java=$(PACKAGE_DIR)/%_Stub.class)
RMI_SKEL_FILES  = $(RMI_SOURCE:%.java=$(PACKAGE_DIR)/%_Skel.class)
ALL_CLASS_FILES = $(CLASS_FILES) $(RMI_STUB_FILES) $(RMI_SKEL_FILES)
JAR_CONTENT_CMD = $(patsubst %,-C $(CLASS_DIR) %,$(JAR_CONTENT))
JSP_LOC         = $(JSP)
  ifeq ($(findstring $$ARCH, CYGWIN_NT),)
	JSP_DIR         = $(shell cygpath -u $(DESTINATION)/../public_html/$(JSP_LOC))
else
	JSP_DIR         = $(DESTINATION)/../public_html/$(JSP_LOC)
endif
JSP_FILES		= $(filter %.jsp, $(JSP_SOURCE))
JSP_DEST_FILES  = $(JSP_FILES:%.jsp=$(JSP_DIR)/%.jsp)
TESTTOOL_DEST_FILES  = $(JSP_FILES:%.jsp=$(JSP_DIR)/%.jsp)
JS_FILES        = $(filter %.js, $(JSP_SOURCE))
JS_DEST_FILES   = $(JS_FILES:%.js=$(JSP_DIR)/%.js)
CSS_FILES       = $(filter %.css, $(JSP_SOURCE))
CSS_DEST_FILES  = $(CSS_FILES:%.css=$(JSP_DIR)/%.css)
GIF_FILES       = $(filter %.gif, $(JSP_SOURCE))
GIF_DEST_FILES  = $(GIF_FILES:%.gif=$(JSP_DIR)/%.gif)
PNG_FILES       = $(filter %.png, $(JSP_SOURCE))
PNG_DEST_FILES  = $(PNG_FILES:%.png=$(JSP_DIR)/%.png)
TPT_FILES       = $(filter %.tpt, $(JSP_SOURCE))
TPT_DEST_FILES  = $(TPT_FILES:%.tpt=$(JSP_DIR)/%.tpt)


ifdef NON_PACKAGE
NON_PACKAGE_LOC = $(NON_PACKAGE)
NON_PKG_DIR     = $(DESTINATION)
DEP_JAVA_FILES  = $(JAVA_FILES:%.java=$(SOURCE_DIR)/$(NON_PACKAGE_LOC)/%.java)
NON_PKG_CLASS_FILES = $(JAVA_FILES:%.java=$(NON_PKG_DIR)/%.class)
NON_PKG_OTHER_FILES = $(NONJAVA_FILES:%=$(NON_PKG_DIR)/%)
DEP_FILE        = $(SOURCE_DIR)/$(NON_PACKAGE_LOC)/.dep
else
DEP_JAVA_FILES  = $(JAVA_FILES:%.java=$(SOURCE_DIR)/$(PACKAGE_LOC)/%.java)
DEP_FILE        = $(SOURCE_DIR)/$(PACKAGE_LOC)/.dep
endif


ALL_TEMP_PROJECT_FILES= $(DEST_DIRS) $(ALL_CLASS_FILES) $(NON_PKG_CLASS_FILES) $(OTHER_FILES) $(JSP_DEST_FILES) $(JS_DEST_FILES) $(GIF_DEST_FILES) $(PNG_DEST_FILES) $(TPT_DEST_FILES) $(TESTTOOL_DEST_FILES) $(CSS_DEST_FILES) 
ifeq ($(findstring $$ARCH, CYGWIN_NT),)
	ALL_PROJECT_FILES = $(shell cygpath -u $(ALL_TEMP_PROJECT_FILES))
else
	ALL_PROJECT_FILES = $(ALL_TEMP_PROJECT_FILES)
endif


# Make a list of all packages involved
ifdef PACKAGE
PACKAGE_LIST    = $(subst .,/,$(PACKAGE))
MAIN_CLASS      = $(MAIN)
MAIN_PACKAGE    = $(PACKAGE)
all : $(ALL_CLASS_FILES) $(TGTS) $(OTHER_FILES)
else
PACKAGE_LIST    = $(subst .,/,$(PACKAGES)) $(subst .,/,$(NODOC_PACKAGES))
all : $(ALL_PROJECT_FILES)
endif
JAVAC_FLAGS    =  -classpath "$(CLASSPATH)" -sourcepath $(SOURCEPATH) -d $(CLASS_DIR) -deprecation -Xlint


clean : 
	$(DELETE)  $(ALL_PROJECT_FILES)

$(PACKAGE_DIR)/%.class :: $(SOURCE_DIR)/$(PACKAGE_LOC)/%.java
	$(JAVAC) $(JAVAC_FLAGS) $<

$(PACKAGE_DIR)/%.properties :: $(SOURCE_DIR)/$(PACKAGE_LOC)/%.properties
	$(DELETE) 644 $@
	$(COPY) $< $@

$(JSP_DIR)/%.jsp :: $(PUBLIC_HTML_DIR)/$(JSP_LOC)/%.jsp
	$(DELETE) $@
	$(COPY) $< $@

$(JSP_DIR)/%.js :: $(PUBLIC_HTML_DIR)/$(JSP_LOC)/%.js
	$(DELETE) $@
	$(COPY) $< $@

$(JSP_DIR)/%.gif :: $(PUBLIC_HTML_DIR)/$(JSP_LOC)/%.gif
	$(DELETE) $@
	$(COPY) $< $@

$(JSP_DIR)/%.png :: $(PUBLIC_HTML_DIR)/$(JSP_LOC)/%.png
	$(DELETE) $@
	$(COPY) $< $@

$(JSP_DIR)/%.tpt :: $(PUBLIC_HTML_DIR)/$(JSP_SOURCE_LOC)/%.tpt
	$(DELETE) $@
	$(COPY) $< $@

$(JSP_DIR)/%.css :: $(PUBLIC_HTML_DIR)/$(JSP_SOURCE_LOC)/%.css
	$(DELETE) $@
	$(COPY) $< $@

basics: $(DEST_DIRS)

$(DEST_DIRS):
	$(MAKEDIR) $@
