#
# @(#)Makefile	1.12 04/03/02
#
# Project Name Project
#
# Author: Govind Thirumalai 
#
#


include $(JAVA_DEV_ROOT)/makefiles/Makefile.include
PACKAGE = core.appui

SOURCE  = \
	UtilBean.java \

RMI_SOURCE =

MAIN =

include $(JAVA_DEV_ROOT)/makefiles/Makefile.rules
