/*
 * AppConstants.java
 *
 * Project Name Project
 *
 * Author: Govind Thirumalai
 */

package app.util;

import java.lang.*;
import java.util.*;

/**
 * This the servlet that is the main entry point.
 *
 * @version	1.0
 * @author	Govind Thirumalai
 * @since	1.0
 */

public class AppConstants {
    public static String MAX_AGE_LABEL;
    public static String MAX_AGE_STR = "maxAge";
    public static String MIN_AGE_LABEL;
    public static String MIN_AGE_STR = "minAge";
    public static String CURRENT_SITE_LABEL;
    public static String MANAGE_SITE_JSP_STR = "ManageSite.jsp";
    public static String MANAGE_SITE_STR = "Manage Site";
    public static String NEW_SITE;
    public static String SITE_BEAN_NAME_STR = "app.appui.SiteBean";
    public static String SITE_ID_LABEL;
    public static String SITE_ID_STR = "siteId";
    public static String SITE_NAME_LABEL;
    public static String SITE_NAME_STR = "siteName";
    public static String SITE_URL_LABEL;
    public static String SITE_URL_STR = "siteUrl";
    public static String ONLINE_REGISTRATION_ONLY_LABEL;
    public static String ONLINE_REGISTRATION_ONLY_STR = "onlineRegistrationOnly";
    public static String REGISTRANT_PHONE_LABEL;
    public static String REGISTRANT_PHONE_STR = "registrantPhone";
    public static String CURRENT_PARTICIPANTEVENT_LABEL;
    public static String CURRENT_REGISTRANTEVENT_LABEL;
    public static String MANAGE_PARTICIPANTEVENT_JSP_STR = "ManageParticipantEvent.jsp";
    public static String MANAGE_PARTICIPANTEVENT_STR = "Manage ParticipantEvent";
    public static String MANAGE_REGISTRANTEVENT_JSP_STR = "ManageRegistrantEvent.jsp";
    public static String MANAGE_REGISTRANTEVENT_STR = "Manage RegistrantEvent";
    public static String NEW_PARTICIPANTEVENT;
    public static String NEW_REGISTRANTEVENT;
    public static String PARTICIPANT_EVENT_ID_LABEL;
    public static String PARTICIPANT_EVENT_ID_STR = "participantEventId";
    public static String PARTICIPANTEVENT_BEAN_NAME_STR = "app.appui.ParticipantEventBean";
    public static String PAYMENT_FEE_LABEL;
    public static String PAYMENT_FEE_STR = "paymentFee";
    public static String PAYMENT_REFERENCE_ID_LABEL;
    public static String PAYMENT_REFERENCE_ID_STR = "paymentReferenceId";
    public static String PAYMENT_TAX_LABEL;
    public static String PAYMENT_TAX_STR = "paymentTax";
    public static String REGISTRANT_EMERGENCY_CONTACT_LABEL;
    public static String REGISTRANT_EMERGENCY_CONTACT_STR = "registrantEmergencyContact";
    public static String REGISTRANT_EMERGENCY_PHONE_LABEL;
    public static String REGISTRANT_EMERGENCY_PHONE_STR = "registrantEmergencyPhone";
    public static String REGISTRANT_EVENT_ID_LABEL;
    public static String REGISTRANT_EVENT_ID_STR = "registrantEventId";
    public static String REGISTRANTEVENT_BEAN_NAME_STR = "app.appui.RegistrantEventBean";
    public static String REGISTRANT_ADDITIONAL_EMAIL_LABEL;
    public static String REGISTRANT_ADDITIONAL_EMAIL_STR = "registrantAdditionalEmail";
    public static String REGISTRANT_LAST_NAME_LABEL;
    public static String REGISTRANT_LAST_NAME_STR = "registrantLastName";
    public static String REGISTRANT_MIDDLE_NAME_LABEL;
    public static String REGISTRANT_MIDDLE_NAME_STR = "registrantMiddleName";
    public static String RESULT_WINNER_REGISTRANT_LABEL;
    public static String RESULT_WINNER_REGISTRANT_STR = "resultWinnerRegistrant";
    public static String BENEFICIARY_ID_LABEL;
    public static String BENEFICIARY_ID_STR = "beneficiaryId";
    public static String BENEFICIARY_NAME_LABEL;
    public static String BENEFICIARY_NAME_STR = "beneficiaryName";
    public static String AGE_CATEGORY_ID_LABEL;
    public static String AGE_CATEGORY_ID_STR = "ageCategoryId";
    public static String AGE_CATEGORY_LABEL;
    public static String AGE_CATEGORY_STR = "ageCategory";
    public static String AGECATEGORY_BEAN_NAME_STR = "app.appui.AgeCategoryBean";
    public static String BENEFECIARY_ID_LABEL;
    public static String BENEFECIARY_ID_STR = "benefeciaryId";
    public static String BENEFECIARY_NAME_LABEL;
    public static String BENEFECIARY_NAME_STR = "benefeciaryName";
    public static String BENEFICIARY_BEAN_NAME_STR = "app.appui.BeneficiaryBean";
    public static String BENEFICIARY_EVENT_LABEL;
    public static String BENEFICIARY_EVENT_STR = "beneficiaryEvent";
    public static String BLOOD_GROUP_ID_LABEL;
    public static String BLOOD_GROUP_ID_STR = "bloodGroupId";
    public static String BLOOD_GROUP_NAME_LABEL;
    public static String BLOOD_GROUP_NAME_STR = "bloodGroupName";
    public static String BLOODGROUP_BEAN_NAME_STR = "app.appui.BloodGroupBean";
    public static String CURRENT_AGECATEGORY_LABEL;
    public static String CURRENT_BENEFICIARY_LABEL;
    public static String CURRENT_BLOODGROUP_LABEL;
    public static String CURRENT_EVENT_LABEL;
    public static String CURRENT_EVENTTYPE_LABEL;
    public static String CURRENT_GENDER_LABEL;
    public static String CURRENT_MEDAL_LABEL;
    public static String CURRENT_PARTICIPANT_LABEL;
    public static String CURRENT_PAYMENTSTATUS_LABEL;
    public static String CURRENT_PAYMENTTYPE_LABEL;
    public static String CURRENT_REGISTRANT_LABEL;
    public static String CURRENT_REGISTRANTPAYMENT_LABEL;
    public static String CURRENT_REGISTRATIONCLASS_LABEL;
    public static String CURRENT_REGISTRATIONSOURCE_LABEL;
    public static String CURRENT_REGISTRATIONTYPE_LABEL;
    public static String CURRENT_RESULT_LABEL;
    public static String CURRENT_TSHIRTSIZE_LABEL;
    public static String EVENT_BEAN_NAME_STR = "app.appui.EventBean";
    public static String EVENT_CHANGES_CLOSE_DATE_LABEL;
    public static String EVENT_CHANGES_CLOSE_DATE_STR = "eventChangesCloseDate";
    public static String EVENT_DESCRIPTION_LABEL;
    public static String EVENT_DESCRIPTION_STR = "eventDescription";
    public static String EVENT_END_DATE_LABEL;
    public static String EVENT_END_DATE_STR = "eventEndDate";
    public static String EVENT_ID_LABEL;
    public static String EVENT_ID_STR = "eventId";
    public static String EVENT_LABEL;
    public static String EVENT_NAME_LABEL;
    public static String EVENT_NAME_STR = "eventName";
    public static String EVENT_REGISTATION_CLOSE_DATE_LABEL;
    public static String EVENT_REGISTATION_CLOSE_DATE_STR = "eventRegistationCloseDate";
    public static String EVENT_START_DATE_LABEL;
    public static String EVENT_START_DATE_STR = "eventStartDate";
    public static String EVENT_STR = "event";
    public static String EVENT_TYPE_DESCRIPTION_LABEL;
    public static String EVENT_TYPE_DESCRIPTION_STR = "eventTypeDescription";
    public static String EVENT_TYPE_END_DATE_LABEL;
    public static String EVENT_TYPE_END_DATE_STR = "eventTypeEndDate";
    public static String EVENT_TYPE_ID_LABEL;
    public static String EVENT_TYPE_ID_STR = "eventTypeId";
    public static String EVENT_TYPE_NAME_LABEL;
    public static String EVENT_TYPE_NAME_STR = "eventTypeName";
    public static String EVENT_TYPE_START_DATE_LABEL;
    public static String EVENT_TYPE_START_DATE_STR = "eventTypeStartDate";
    public static String EVENT_TYPE_VENUE_LABEL;
    public static String EVENT_TYPE_VENUE_STR = "eventTypeVenue";
    public static String EVENTTYPE_BEAN_NAME_STR = "app.appui.EventTypeBean";
    public static String GENDER_BEAN_NAME_STR = "app.appui.GenderBean";
    public static String GENDER_ID_LABEL;
    public static String GENDER_ID_STR = "genderId";
    public static String GENDER_NAME_LABEL;
    public static String GENDER_NAME_STR = "genderName";
    public static String MANAGE_AGECATEGORY_JSP_STR = "ManageAgeCategory.jsp";
    public static String MANAGE_AGECATEGORY_STR = "Manage AgeCategory";
    public static String MANAGE_BENEFICIARY_JSP_STR = "ManageBeneficiary.jsp";
    public static String MANAGE_BENEFICIARY_STR = "Manage Beneficiary";
    public static String MANAGE_BLOODGROUP_JSP_STR = "ManageBloodGroup.jsp";
    public static String MANAGE_BLOODGROUP_STR = "Manage BloodGroup";
    public static String MANAGE_EVENT_JSP_STR = "ManageEvent.jsp";
    public static String MANAGE_EVENT_STR = "Manage Event";
    public static String MANAGE_EVENTTYPE_JSP_STR = "ManageEventType.jsp";
    public static String MANAGE_EVENTTYPE_STR = "Manage EventType";
    public static String MANAGE_GENDER_JSP_STR = "ManageGender.jsp";
    public static String MANAGE_GENDER_STR = "Manage Gender";
    public static String MANAGE_MEDAL_JSP_STR = "ManageMedal.jsp";
    public static String MANAGE_MEDAL_STR = "Manage Medal";
    public static String MANAGE_PARTICIPANT_JSP_STR = "ManageParticipant.jsp";
    public static String MANAGE_PARTICIPANT_STR = "Manage Participant";
    public static String MANAGE_PAYMENTSTATUS_JSP_STR = "ManagePaymentStatus.jsp";
    public static String MANAGE_PAYMENTSTATUS_STR = "Manage PaymentStatus";
    public static String MANAGE_PAYMENTTYPE_JSP_STR = "ManagePaymentType.jsp";
    public static String MANAGE_PAYMENTTYPE_STR = "Manage PaymentType";
    public static String MANAGE_REGISTRANT_JSP_STR = "ManageRegistrant.jsp";
    public static String MANAGE_REGISTRANT_STR = "Manage Registrant";
    public static String MANAGE_REGISTRANTPAYMENT_JSP_STR = "ManageRegistrantPayment.jsp";
    public static String MANAGE_REGISTRANTPAYMENT_STR = "Manage RegistrantPayment";
    public static String MANAGE_REGISTRATIONCLASS_JSP_STR = "ManageRegistrationClass.jsp";
    public static String MANAGE_REGISTRATIONCLASS_STR = "Manage RegistrationClass";
    public static String MANAGE_REGISTRATIONSOURCE_JSP_STR = "ManageRegistrationSource.jsp";
    public static String MANAGE_REGISTRATIONSOURCE_STR = "Manage RegistrationSource";
    public static String MANAGE_REGISTRATIONTYPE_JSP_STR = "ManageRegistrationType.jsp";
    public static String MANAGE_REGISTRATIONTYPE_STR = "Manage RegistrationType";
    public static String MANAGE_RESULT_JSP_STR = "ManageResult.jsp";
    public static String MANAGE_RESULT_STR = "Manage Result";
    public static String MANAGE_TSHIRTSIZE_JSP_STR = "ManageTShirtSize.jsp";
    public static String MANAGE_TSHIRTSIZE_STR = "Manage TShirtSize";
    public static String MEDAL_BEAN_NAME_STR = "app.appui.MedalBean";
    public static String MEDAL_ID_LABEL;
    public static String MEDAL_ID_STR = "medalId";
    public static String MEDAL_NAME_LABEL;
    public static String MEDAL_NAME_STR = "medalName";
    public static String MEDAL_RANK_LABEL;
    public static String MEDAL_RANK_STR = "medalRank";
    public static String NEW_AGECATEGORY;
    public static String NEW_BENEFICIARY;
    public static String NEW_BLOODGROUP;
    public static String NEW_EVENT;
    public static String NEW_EVENTTYPE;
    public static String NEW_GENDER;
    public static String NEW_MEDAL;
    public static String NEW_PARTICIPANT;
    public static String NEW_PAYMENTSTATUS;
    public static String NEW_PAYMENTTYPE;
    public static String NEW_REGISTRANT;
    public static String NEW_REGISTRANTPAYMENT;
    public static String NEW_REGISTRATIONCLASS;
    public static String NEW_REGISTRATIONSOURCE;
    public static String NEW_REGISTRATIONTYPE;
    public static String NEW_RESULT;
    public static String NEW_TSHIRTSIZE;
    public static String PARTICIPANT_AGE_CATEGORY_LABEL;
    public static String PARTICIPANT_AGE_CATEGORY_STR = "participantAgeCategory";
    public static String PARTICIPANT_BEAN_NAME_STR = "app.appui.ParticipantBean";
    public static String PARTICIPANT_BIB_NO_LABEL;
    public static String PARTICIPANT_BIB_NO_STR = "participantBibNo";
    public static String PARTICIPANT_BLOOD_GROUP_LABEL;
    public static String PARTICIPANT_BLOOD_GROUP_STR = "participantBloodGroup";
    public static String PARTICIPANT_CELL_PHONE_LABEL;
    public static String PARTICIPANT_CELL_PHONE_STR = "participantCellPhone";
    public static String PARTICIPANT_DATE_OF_BIRTH_LABEL;
    public static String PARTICIPANT_DATE_OF_BIRTH_STR = "participantDateOfBirth";
    public static String PARTICIPANT_EMAIL_LABEL;
    public static String PARTICIPANT_EMAIL_STR = "participantEmail";
    public static String PARTICIPANT_EMERGENCY_CONTACT_LABEL;
    public static String PARTICIPANT_EMERGENCY_CONTACT_STR = "participantEmergencyContact";
    public static String PARTICIPANT_EMERGENCY_PHONE_LABEL;
    public static String PARTICIPANT_EMERGENCY_PHONE_STR = "participantEmergencyPhone";
    public static String PARTICIPANT_EVENT_LABEL;
    public static String PARTICIPANT_EVENT_STR = "participantEvent";
    public static String PARTICIPANT_EVENT_TYPE_LABEL;
    public static String PARTICIPANT_EVENT_TYPE_STR = "participantEventType";
    public static String PARTICIPANT_FIRST_NAME_LABEL;
    public static String PARTICIPANT_FIRST_NAME_STR = "participantFirstName";
    public static String PARTICIPANT_GENDER_LABEL;
    public static String PARTICIPANT_GENDER_STR = "participantGender";
    public static String PARTICIPANT_GROUP_LABEL;
    public static String PARTICIPANT_GROUP_STR = "participantGroup";
    public static String PARTICIPANT_ID_LABEL;
    public static String PARTICIPANT_ID_STR = "participantId";
    public static String PARTICIPANT_LAST_NAME_LABEL;
    public static String PARTICIPANT_LAST_NAME_STR = "participantLastName";
    public static String PARTICIPANT_MIDDLE_NAME_LABEL;
    public static String PARTICIPANT_MIDDLE_NAME_STR = "participantMiddleName";
    public static String PARTICIPANT_T_SHIRT_SIZE_LABEL;
    public static String PARTICIPANT_T_SHIRT_SIZE_STR = "participantTShirtSize";
    public static String PARTICIPANT_TYPE_LABEL;
    public static String PARTICIPANT_TYPE_STR = "participantType";
    public static String PAYMENT_ADDITIONAL_AMOUNT_LABEL;
    public static String PAYMENT_ADDITIONAL_AMOUNT_STR = "paymentAdditionalAmount";
    public static String PAYMENT_AMOUNT_LABEL;
    public static String PAYMENT_AMOUNT_STR = "paymentAmount";
    public static String PAYMENT_DATE_LABEL;
    public static String PAYMENT_DATE_STR = "paymentDate";
    public static String PAYMENT_DETAILS_LABEL;
    public static String PAYMENT_DETAILS_STR = "paymentDetails";
    public static String PAYMENT_STATUS_ID_LABEL;
    public static String PAYMENT_STATUS_ID_STR = "paymentStatusId";
    public static String PAYMENT_STATUS_LABEL;
    public static String PAYMENT_STATUS_NAME_LABEL;
    public static String PAYMENT_STATUS_NAME_STR = "paymentStatusName";
    public static String PAYMENT_STATUS_STR = "paymentStatus";
    public static String PAYMENT_TOWARDS_LABEL;
    public static String PAYMENT_TOWARDS_STR = "paymentTowards";
    public static String PAYMENT_TYPE_ID_LABEL;
    public static String PAYMENT_TYPE_ID_STR = "paymentTypeId";
    public static String PAYMENT_TYPE_LABEL;
    public static String PAYMENT_TYPE_NAME_LABEL;
    public static String PAYMENT_TYPE_NAME_STR = "paymentTypeName";
    public static String PAYMENT_TYPE_STR = "paymentType";
    public static String PAYMENTSTATUS_BEAN_NAME_STR = "app.appui.PaymentStatusBean";
    public static String PAYMENTTYPE_BEAN_NAME_STR = "app.appui.PaymentTypeBean";
    public static String RECEIPT_DATE_LABEL;
    public static String RECEIPT_DATE_STR = "receiptDate";
    public static String REGISTRANT_ADDRESS_LABEL;
    public static String REGISTRANT_ADDRESS_STR = "registrantAddress";
    public static String REGISTRANT_BEAN_NAME_STR = "app.appui.RegistrantBean";
    public static String REGISTRANT_BENEFICIARY_LABEL;
    public static String REGISTRANT_BENEFICIARY_STR = "registrantBeneficiary";
    public static String REGISTRANT_CITY_LABEL;
    public static String REGISTRANT_CITY_STR = "registrantCity";
    public static String REGISTRANT_CLASS_LABEL;
    public static String REGISTRANT_CLASS_STR = "registrantClass";
    public static String REGISTRANT_EMAIL_LABEL;
    public static String REGISTRANT_EMAIL_STR = "registrantEmail";
    public static String REGISTRANT_EVENT_LABEL;
    public static String REGISTRANT_EVENT_STR = "registrantEvent";
    public static String REGISTRANT_ID_LABEL;
    public static String REGISTRANT_ID_STR = "registrantId";
    public static String REGISTRANT_LABEL;
    public static String REGISTRANT_NAME_LABEL;
    public static String REGISTRANT_NAME_STR = "registrantName";
    public static String REGISTRANT_PAN_LABEL;
    public static String REGISTRANT_PAN_STR = "registrantPan";
    public static String REGISTRANT_PAYMENT_ID_LABEL;
    public static String REGISTRANT_PAYMENT_ID_STR = "registrantPaymentId";
    public static String REGISTRANT_PHONE_NUMBER_LABEL;
    public static String REGISTRANT_PHONE_NUMBER_STR = "registrantPhoneNumber";
    public static String REGISTRANT_PINCODE_LABEL;
    public static String REGISTRANT_PINCODE_STR = "registrantPincode";
    public static String REGISTRANT_SOURCE_LABEL;
    public static String REGISTRANT_SOURCE_STR = "registrantSource";
    public static String REGISTRANT_STATE_LABEL;
    public static String REGISTRANT_STATE_STR = "registrantState";
    public static String REGISTRANT_STR = "registrant";
    public static String REGISTRANT_TYPE_LABEL;
    public static String REGISTRANT_TYPE_STR = "registrantType";
    public static String REGISTRANTPAYMENT_BEAN_NAME_STR = "app.appui.RegistrantPaymentBean";
    public static String REGISTRATION_CLASS_ID_LABEL;
    public static String REGISTRATION_CLASS_ID_STR = "registrationClassId";
    public static String REGISTRATION_CLASS_NAME_LABEL;
    public static String REGISTRATION_CLASS_NAME_STR = "registrationClassName";
    public static String REGISTRATION_CLASS_VALUE_LABEL;
    public static String REGISTRATION_CLASS_VALUE_STR = "registrationClassValue";
    public static String REGISTRATION_EVENT_LABEL;
    public static String REGISTRATION_EVENT_STR = "registrationEvent";
    public static String REGISTRATION_FREE_TICKETS_LABEL;
    public static String REGISTRATION_FREE_TICKETS_STR = "registrationFreeTickets";
    public static String REGISTRATION_SOURCE_ID_LABEL;
    public static String REGISTRATION_SOURCE_ID_STR = "registrationSourceId";
    public static String REGISTRATION_SOURCE_NAME_LABEL;
    public static String REGISTRATION_SOURCE_NAME_STR = "registrationSourceName";
    public static String REGISTRATION_TYPE_ID_LABEL;
    public static String REGISTRATION_TYPE_ID_STR = "registrationTypeId";
    public static String REGISTRATION_TYPE_LABEL;
    public static String REGISTRATION_TYPE_NAME_LABEL;
    public static String REGISTRATION_TYPE_NAME_STR = "registrationTypeName";
    public static String REGISTRATION_TYPE_STR = "registrationType";
    public static String REGISTRATIONCLASS_BEAN_NAME_STR = "app.appui.RegistrationClassBean";
    public static String REGISTRATIONSOURCE_BEAN_NAME_STR = "app.appui.RegistrationSourceBean";
    public static String REGISTRATIONTYPE_BEAN_NAME_STR = "app.appui.RegistrationTypeBean";
    public static String RESULT_BEAN_NAME_STR = "app.appui.ResultBean";
    public static String RESULT_EVENT_LABEL;
    public static String RESULT_EVENT_STR = "resultEvent";
    public static String RESULT_EVENT_TYPE_LABEL;
    public static String RESULT_EVENT_TYPE_STR = "resultEventType";
    public static String RESULT_ID_LABEL;
    public static String RESULT_ID_STR = "resultId";
    public static String RESULT_MEDAL_LABEL;
    public static String RESULT_MEDAL_STR = "resultMedal";
    public static String RESULT_SCORE_LABEL;
    public static String RESULT_SCORE_STR = "resultScore";
    public static String RESULT_TIMING_LABEL;
    public static String RESULT_TIMING_STR = "resultTiming";
    public static String RESULT_WINNER_LABEL;
    public static String RESULT_WINNER_REGISTRRANT_LABEL;
    public static String RESULT_WINNER_REGISTRRANT_STR = "resultWinnerRegistrrant";
    public static String RESULT_WINNER_STR = "resultWinner";
    public static String T_SHIRT_GENDER_LABEL;
    public static String T_SHIRT_GENDER_STR = "tShirtGender";
    public static String T_SHIRT_SIZE_ID_LABEL;
    public static String T_SHIRT_SIZE_ID_STR = "tShirtSizeId";
    public static String T_SHIRT_SIZE_NAME_LABEL;
    public static String T_SHIRT_SIZE_NAME_STR = "tShirtSizeName";
    public static String TSHIRTSIZE_BEAN_NAME_STR = "app.appui.TShirtSizeBean";
    public static String CURRENT_MENU_LABEL;
    public static String MANAGE_MENU_JSP_STR = "ManageMenu.jsp";
    public static String MANAGE_MENU_STR = "Manage Menu";
    public static String MENU_BEAN_NAME_STR = "app.appui.MenuBean";
    public static String MENU_ID_LABEL;
    public static String MENU_ID_STR = "menuId";
    public static String MENU_NAME_LABEL;
    public static String MENU_NAME_STR = "menuName";
    public static String MENU_ORDER_LABEL;
    public static String MENU_ORDER_STR = "menuOrder";
    public static String NEW_MENU;
    public static String PARENT_MENU_ID_LABEL;
    public static String PARENT_MENU_ID_STR = "parentMenuId";
    public static String NEW_PARENT_MENU;
    public static String URL_LABEL;
    public static String URL_STR = "url";
    public static String PERMISSION_LABEL;
    public static String PERMISSION_STR = "permission";
    public static String ACCESS_LABEL;
    public static String ACCESS_STR = "access";
    public static String ACL_BEAN_NAME_STR = "app.appui.AclBean";
    public static String ACL_ID_LABEL;
    public static String ACL_ID_STR = "aclId";
    public static String ACL_PAGE_LABEL;
    public static String ACL_PAGE_STR = "aclId";
    public static String CURRENT_ACL_LABEL;
    public static String MANAGE_ACL_JSP_STR = "ManageAcl.jsp";
    public static String MANAGE_ACL_STR = "Manage Acl";
    public static String NEW_ACL;
    public static String USERS_ID_LABEL;
    public static String USERS_ID_STR = "usersId";

    public static String ROLE_BEAN_NAME_STR = "app.appui.RoleBean";
    public static String ROLE_ID_LABEL;
    public static String ROLE_ID_STR = "roleId";
    public static String IS_VALID_STR = "isValid";
    public static String ROLE_NAME_LABEL;
    public static String ROLE_NAME_STR = "roleName";
    public static String MANAGE_ROLE_JSP_STR = "ManageRole.jsp";
    public static String MANAGE_ROLE_STR = "Manage Role";
    public static final String MANAGE_USERS_JSP_STR = "ManageUsers.jsp";
    public static final String REGISTRATION_JSP_STR = "Registration.jsp";
    public static final String RESET_PASSWORD_JSP_STR = "ResetPassword.jsp";
    public static final String MANAGE_USERS_STR = "Manage Users";
    public static final String LOGIN_JSP_STR = "Login.jsp";
    public static final String LOGOUT_JSP_STR = "Logout.jsp";

    public static final String DEFAULT_JSP_STR = MANAGE_USERS_JSP_STR;

    public static final String LOGIN_REQUIRED_STR = "loginRequired";
    public static final String LOGIN = "login";
    public static String USER_NAME_STR = "username";
    public static String USER_ID_STR = "userId";
    public static String MODIFY_USER_STR = "modifyUser";
    public static String MODIFY_ROLE_STR = "modifyRole";
    public static String USER_PROPERTIES_STR = "userproperties";
    public static String PASSWORD_STR = "password";
    public static String NEW_PASSWORD_STR = "newPassword";
    public static String RE_PASSWORD_STR = "rePassword";
    public static String NEW_USERNAME_STR = "newUsername";
    public static String ALREADY_LOGGED_IN_STR = "alreadyLoggedIn";
    public static String ADMIN_STR = "admin";
    public static String NORMAL_STR = "normal";
    public static String GUEST_STR = "guest";
    public static String ERROR_STR = "errorString";
    public static String STATUS_STR = "statusString";
    public static String ADMINISTRATOR_STR = "Administrator";
    public static String NORMAL_USER_STR = "Normal User";
    public static String GUEST_USER_STR = "Guest";

    public static String NEW_ROLE;
    public static String IS_VALID_LABEL;
    public static String REGISTRATION_LABEL;
    public static String RESET_PASSWORD_LABEL;
    public static String USER_ID_LABEL;
    public static String PASSWORD_LABEL;
    public static String CURRENT_USERS_LABEL;
    public static String CURRENT_ROLE_LABEL;
    public static String NEW_PASSWORD_LABEL;
    public static String RETYPE_PASSWORD_LABEL;
    public static String NEW_USER;
    public static String LOGIN_REQUIRED_URLS;
    public static String LOGOUT_STR;
    public static String LOGIN_STR;
    public static String EMAIL_LABEL;
    public static String EMAIL_SUBJECT;
    public static String EMAIL_BODY_HEADER;
    public static String EMAIL_BODY_FOOTER;
    public static String EMAIL_STR = "email";
    public static String JSP_BASE;
    public static String SECURITY_MANAGEMENT_LABEL;
    public static String HOME_LABEL;
    public static String POST_URL;
    public static String DB_TYPE;
	public static String DB_OPERATION_LABEL;

	public static String SMTP_HOST;
	public static boolean SMTP_DEBUG;
	public static String EMAIL_FROM;
	public static String EMAIL_USERNAMES;
	public static String RECEIPT_NO_PREFIX;
	public static String RECEIPT_TEMPLATE;
	public static String RECEIPT_MAIL_BODY_TEMPLATE;
	public static String RECEIPT_MAIL_SUBJECT;
	public static int SITE_ID = 1;
	public static int ONLINE_REGISTRANT_ID = 1;
};

