#
# @(#)Makefile	1.4 04/08/19
#
# Project Name Project
#
# Author: Govind Thirumalai 
#
#



include $(JAVA_DEV_ROOT)/makefiles/Makefile.include
PACKAGE = app.util

SOURCE  = \
	AppConstants.java \
	App.java \
	app.properties \
	apptemplate.properties \

RMI_SOURCE =

MAIN =

include $(JAVA_DEV_ROOT)/makefiles/Makefile.rules
