#
# @(#)Makefile	1.3 01/12/10
#
# Patch Project
#
# Author: Govind Thirumalai 
#
#


include $(JAVA_DEV_ROOT)/makefiles/Makefile.include

PACKAGE = core.util

SOURCE  = \
	AppException.java \
	DebugException.java \
	DebugInterface.java \
	DebugHandler.java \
	Util.java \
	SendMail.java \
	Cache.java \
	Cacheable.java \
	CalendarLocalizer.java \
	CollectionHandler.java \
	Constants.java \
	CountryToLocale.java \
	ExceptionHandler.java \
	GenericDebug.java \
	Localizer.java \
	MultipartRequest.java \
	RequestURL.java \
	site.properties \
	LocalizerData.properties \
	PrintfFormat.java \
	CmdlineInvoke.java \
	PasswordCrypt.java \

RMI_SOURCE =

MAIN =


include $(JAVA_DEV_ROOT)/makefiles/Makefile.rules
