#
# @(#)Makefile	1.3 04/03/02
#
# Project Name Project
#
# Author: Govind Thirumalai 
#
#


include $(JAVA_DEV_ROOT)/makefiles/Makefile.include
PACKAGE = core.db

SOURCE  = \
	CallableSQLStatement.java \
	DBException.java \
	DBManager.java \
	DBUtil.java \
	ObjectRelationalMap.java \
	PersistenceFactory.java \
	Persistent.java \
	PersistentObject.java \
	PreparedSQLStatement.java \
	SQLParam.java \
	SQLStatement.java \
	TransactionContext.java \
	db.properties \
	dbtemplate.properties \
	persistence.properties

RMI_SOURCE =

MAIN =

include $(JAVA_DEV_ROOT)/makefiles/Makefile.rules
